config/routes.rb
Rails.application.routes.draw do
  resources :costs
  get '/', to: 'girls#home', as: 'home'
  get '/test', to: 'costs#test'
  resources :girls
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cost.rb
class Cost < ApplicationRecord
  validates :year, presence: true
  validates :month, presence: true
  validates :day, presence: true
  validates :costsfile, presence: true  
  mount_uploader :costsfile, CostsfileUploader
end

app/models/girl.rb
class Girl < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/money_management.rb
class MoneyManagement < ApplicationRecord
  belongs_to :costs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: %i[ show edit update destroy ]

  # GET /costs or /costs.json
  def index
    @costs = Cost.all
    
  end

  # GET /costs/1 or /costs/1.json
  def show
    @cost_file = Roo::Excelx.new("./public/uploads/cost/costsfile/#{@cost.id}/#{@cost[:costsfile]}").sheet(0)
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs or /costs.json
  def create
    @cost = Cost.new(cost_params)
    respond_to do |format|
      if @cost.save
        raise
        format.html { redirect_to costs_path, notice: "Cost was successfully created." }
        format.json { render :index, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1 or /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to cost_url(@cost), notice: "Cost was successfully updated." }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1 or /costs/1.json
  def destroy
    @cost.destroy

    respond_to do |format|
      format.html { redirect_to costs_url, notice: "Cost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def test
    casename="dashbord"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cost_params
      params.require(:cost).permit(:year, :month, :day, :costsfile)
    end

    def money_managements_param
      params.require(:money_managements).permit(:category, :fee, :remarks)
    end

end

app/controllers/girls_controller.rb
class GirlsController < ApplicationController
  before_action :set_girl, only: %i[ show edit update destroy ]

  def home
    @htmlclass = "h-100"
  end
  
  # GET /girls or /girls.json
  def index
    @girls = Girl.all
    @htmlclass = "h-auto"
  end

  # GET /girls/1 or /girls/1.json
  def show
  end

  # GET /girls/new
  def new
    @girl = Girl.new
  end

  # GET /girls/1/edit
  def edit
  end

  # POST /girls or /girls.json
  def create
    @girl = Girl.new(girl_params)
    respond_to do |format|
      if @girl.save
        format.html { redirect_to girl_url(@girl), notice: "Girl was successfully created." }
        format.json { render :show, status: :created, location: @girl }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @girl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /girls/1 or /girls/1.json
  def update
    respond_to do |format|
      if @girl.update(girl_params)
        format.html { redirect_to girl_url(@girl), notice: "Girl was successfully updated." }
        format.json { render :show, status: :ok, location: @girl }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @girl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /girls/1 or /girls/1.json
  def destroy
    @girl.destroy

    respond_to do |format|
      format.html { redirect_to girls_url, notice: "Girl was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_girl
      girl = Girl.find(params[:id])
      @girls = Girl.where(name: girl.name)
      # raise
    end

    # Only allow a list of trusted parameters through.
    def girl_params
      params.require(:girl).permit(:name, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/girls_helper.rb
module GirlsHelper
end

app/views/costs/_cost.html.erb
<div id="<%= dom_id cost %>">
  <p>
    <strong>Y:M:D</strong>
    <%= cost.year %>:<%= cost.month %>:<%= cost.day %>
  </p>

  <p><%= @cost_file %></p>
  
</div>

app/views/costs/_form.html.erb
<%= form_with(model: cost) do |form| %>
  <% if cost.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
        <% cost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :month, style: "display: block" %>
    <%= form.number_field :month %>
  </div>

  <div>
    <%= form.label :day, style: "display: block" %>
    <%= form.number_field :day %>
  </div>

  <div>
    <%= form.label :costsfile, style: "display: block" %>
    <%= form.file_field :costsfile %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Editing cost</h1>

<%= render "form", cost: @cost %>

<br>

<div>
  <%= link_to "Show this cost", @cost %> |
  <%= link_to "Back to costs", costs_path %>
</div>

app/views/costs/index.html.erb
<%= stylesheet_link_tag 'DASHBOARD/dashboard' %>
<%
=begin%>
 <p style="color: green"><%= notice %></p>

<h1>Costs</h1>

<%= link_to "New cost", new_cost_path %>

<div id="costs">
  <% @costs.each do |cost| %>
    <%= render cost %>
    <p>
      <%= link_to "Show this cost", cost %>
    </p>
  <% end %>
</div> 
<%
=end%>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Company name</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="#">Sign out</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Orders
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>

      <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

      <h2>LOG</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Year</th>
              <th scope="col">Month</th>
              <th scope="col">Day</th>
              <th scope="col">Header</th>
            </tr>
          </thead>
          <tbody>
            <% @costs.each do |cost| %>
              <tr>
                <td><%= cost.year %></td>
                <td><%= cost.month %></td>
                <td><%= cost.day %></td>
                <td><%= link_to(cost[:costsfile], cost_path(cost.id)) %></td>
              </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
<%= javascript_include_tag "DASHBOARD/dashboard.js" %>

app/views/costs/new.html.erb
<h1>New cost</h1>

<%= render "form", cost: @cost %>

<br>

<div>
  <%= link_to "Back to costs", costs_path %>
</div>

app/views/costs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cost %>

<div>
  <%= link_to "Edit this cost", edit_cost_path(@cost) %> |
  <%= link_to "Back to costs", costs_path %>

  <%= button_to "Destroy this cost", @cost, method: :delete %>
</div>

app/views/costs/test.html.erb
<body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Company name</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="#">Sign out</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Orders
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>

      <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

      <h2>Section title</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td>text</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>placeholder</td>
              <td>irrelevant</td>
              <td>visual</td>
              <td>layout</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>data</td>
              <td>rich</td>
              <td>dashboard</td>
              <td>tabular</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>information</td>
              <td>placeholder</td>
              <td>illustrative</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,004</td>
              <td>text</td>
              <td>random</td>
              <td>layout</td>
              <td>dashboard</td>
            </tr>
            <tr>
              <td>1,005</td>
              <td>dashboard</td>
              <td>irrelevant</td>
              <td>text</td>
              <td>placeholder</td>
            </tr>
            <tr>
              <td>1,006</td>
              <td>dashboard</td>
              <td>illustrative</td>
              <td>rich</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,007</td>
              <td>placeholder</td>
              <td>tabular</td>
              <td>information</td>
              <td>irrelevant</td>
            </tr>
            <tr>
              <td>1,008</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td>text</td>
            </tr>
            <tr>
              <td>1,009</td>
              <td>placeholder</td>
              <td>irrelevant</td>
              <td>visual</td>
              <td>layout</td>
            </tr>
            <tr>
              <td>1,010</td>
              <td>data</td>
              <td>rich</td>
              <td>dashboard</td>
              <td>tabular</td>
            </tr>
            <tr>
              <td>1,011</td>
              <td>information</td>
              <td>placeholder</td>
              <td>illustrative</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,012</td>
              <td>text</td>
              <td>placeholder</td>
              <td>layout</td>
              <td>dashboard</td>
            </tr>
            <tr>
              <td>1,013</td>
              <td>dashboard</td>
              <td>irrelevant</td>
              <td>text</td>
              <td>visual</td>
            </tr>
            <tr>
              <td>1,014</td>
              <td>dashboard</td>
              <td>illustrative</td>
              <td>rich</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>random</td>
              <td>tabular</td>
              <td>information</td>
              <td>text</td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
      <script src="javascript/dashboard.js"></script>
  </body>

app/views/girls/_form.html.erb
<%= form_with(model: girl) do |form| %>
  <% if girl.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(girl.errors.count, "error") %> prohibited this girl from being saved:</h2>

      <ul>
        <% girl.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content, class:"form-control" %>
  </div>

  <div class="mb-3">
     <%= form.label :image %>
     <%= form.file_field :image %>
  </div>

  <div class="mb-3 form-check">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/girls/_girl.html.erb
<div id="<%= dom_id girl %>" class="uk-card uk-card-default uk-card-hover uk-card-body" >
  <h3 class="uk-card-title"><%= girl.name %></h3>
  
  <p>
    <%= image_tag(girl.image.to_s) %>
  </p>

  <p>
    <%= link_to "", girl,class: 'test' %>
  </p>
</div>

app/views/girls/edit.html.erb
<h1>Editing girl</h1>

<%= render "form", girl: @girl %>

<br>

<div>
  <%= link_to "Show this girl", @girl %> |
  <%= link_to "Back to girls", girls_path %>
</div>

app/views/girls/home.html.erb
<%= stylesheet_link_tag 'COVER/cover' %>

  <body class="d-flex h-100 text-center text-bg-dark">
    
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="mb-auto">
        <div>
          <%= link_to "Home", home_path, class:"float-md-start mb-0" %>
          <nav class="nav nav-masthead justify-content-center float-md-end">
            <%= link_to "Girls", girls_path, class:"nav-link fw-bold py-1 px-0 active" %>
            <%= link_to "CostManegement", costs_path, class:"nav-link fw-bold py-1 px-0" %>
            <%= link_to "Food", "#", class:"nav-link fw-bold py-1 px-0" %>
          </nav>
        </div>
      </header>

      <main class="px-3">
        <h1>Today</h1>
        <p class="lead">example</p>
        <p class="lead">
          <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
        </p>
      </main>

      <footer class="mt-auto text-white-50">
        <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
      </footer>
    </div>
  </body>

app/views/girls/index.html.erb
<%= stylesheet_link_tag 'COVER/cover' %>

<p style="color: green"><%= notice %></p>
<body class="d-flex h-100 text-center text-bg-dark">
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="mb-auto">
        <div>
          <%= link_to "Home", home_path, class:"float-md-start mb-0" %>
          <nav class="nav nav-masthead justify-content-center float-md-end">
            <%= link_to "Girls", girls_path, class:"nav-link fw-bold py-1 px-0 active" %>
            <%= link_to "CostManegement", costs_path, class:"nav-link fw-bold py-1 px-0" %>
            <%= link_to "Food", "#", class:"nav-link fw-bold py-1 px-0" %>
          </nav>
        </div>
      </header>
<div id="girls" class="uk-child-width-1-2@m" uk-grid uk-scrollspy="cls: uk-animation-fade; target: .uk-card; delay: 500; repeat: true">
  <% @girls.each do |girl| %>
    <%= render girl %>
  <% end %>
</div>
  </body>

app/views/girls/new.html.erb
<h1>New girl</h1>

<%= render "form", girl: @girl %>

<br>

<div>
  <%= link_to "Back to girls", girls_path %>
</div>

app/views/girls/show.html.erb
<div id="girls" class="uk-child-width-1-2@m" uk-grid uk-scrollspy="cls: uk-animation-fade; target: .uk-card; delay: 500; repeat: true">
  <% @girls.each do |girl| %>
    <div id="<%= dom_id girl %>" class="uk-card uk-card-default uk-card-hover uk-card-body" >
      
      <p>
        <%= image_tag(girl.image.to_s) %>
      </p>

      <p>
        <%= link_to "", girl,class: 'test' %>
      </p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="<%= @htmlclass %>">
  <head>
    <title>RailsHome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!---Reflection about Ulkit(css)--->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.15.1/dist/css/uikit.min.css" />
    <!---Reflection about Ulkit(js)--->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.15.1/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.15.1/dist/js/uikit-icons.min.js"></script>

    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>
    <%= yield %>
  </body>
</html>